steps:
- id: 'Rebuild Node Files'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  entrypoint: 'bash'
  args:
  - '-c' # pass what follows as a command to bash
  - |
    echo $COMMIT_SHA > buildID
    npm install

- id: 'Rebuild Node Files'
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: 'Deploy to App Engine'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml','--version=$COMMIT_SHA','--quiet']
  waitFor: ['Rebuild Node Files']

- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$_IMAGE_REPO/gcpdemo:$BUILD_ID', '.']
  waitFor: ['Rebuild Node Files']

- id: 'Push to Registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$_IMAGE_REPO/gcpdemo:$BUILD_ID"]
  waitFor: ['Create Container']

# This step deploys the new version of our container image
# to the specified  Kubernetes Engine cluster.
- id: 'Deploy to K8s'
  name: 'gcr.io/cloud-builders/kubectl'
  waitFor: ['Push to Registry']
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend-production'
  - 'webserver=gcr.io/$_IMAGE_REPO/gcpdemo:$BUILD_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=$_CLOUDSDK_COMPUTE_ZONE'
  - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLOUDSDK_CONTAINER_CLUSTER'
#secrets:
#- kmsKeyName: projects/bkauf-cloud-build/locations/global/keyRings/cloudbuild/cryptoKeys/weatherapi
#  secretEnv:
#    WEATHERAPI: $#ȬF`]$I?)"ׄ~v#(I)_,czkQB.x9yRڴϊI8+0FkWzI9BiUi2#/8*#b
#
