steps:
#- id: 'Unit tests'
#  name: 'ubuntu'
#  args: ['bash', './myscript.bash']

- id: 'Build'
  name: 'gcr.io/cloud-builders/npm'
  #dir: 'frontend'
  args: [ 'run', 'build' ]
  
#- name: 'gcr.io/cloud-builders/docker'
#  args: ['build', '--tag=gcr.io/$PROJECT_ID/gcpdemo:$TAG_NAME', '.']
#  args: ['cp', '-r', 'k8s/*', 'gs://$PROJECT_ID-kubernetes-manifests']
#  images: ['gcr.io/$PROJECT_ID/gcpdemo:$TAG_NAME']
- id: 'Deploy'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy'] timeout: '1600s'
