steps:
#- id: 'Unit tests'
#  name: 'ubuntu'
#  entrypoint: "bash"
#  args: ['$(< animal.sh) > _ANIMAL']

- id: ' Rebuild Node Files'
  name: 'gcr.io/cloud-builders/npm'
  args: ['rebuild']

- id: 'Copy Files into Source Folder'
  name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://$PROJECT_ID-pictures/dogs/*', 'public/images/']

- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/cicd-event-march25th-prod/gcpdemo:$TAG_NAME', '.']

- id: 'Push Container to Production registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/cicd-event-march25th-prod/gcpdemo:$TAG_NAME"]

- id: 'Deploy to Production Cluster'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend-production'
  - 'my-container=gcr.io/cicd-event-march25th-prod/gcpdemo:$TAG_NAME'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=prod-cluster-1'
  - 'CLOUDSDK_CORE_PROJECT=cicd-event-march25th-prod'
options:
 machineType: 'N1_HIGHCPU_8'
