steps:
#- id: 'Unit tests'
#  name: 'ubuntu'
#  entrypoint: "bash"
#  args: ['cat animal.sh)" > _ANIMAL']

- id: ' Rebuild Node Files'
  name: 'gcr.io/cloud-builders/npm'
  args: ['rebuild']

- id: 'copy files into source folder'
  name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://$PROJECT_ID-pictures/dogs/*', 'public/images/homepage/']



- id: 'Create Container'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/gcpdemo:$TAG_NAME', '.']
#  args: ['cp', '-r', 'k8s/*', 'gs://$PROJECT_ID-kubernetes-manifests']
- id: 'Push Container to Staging Registry'
  name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/gcpdemo:$TAG_NAME"]

- id: 'Deploy to Staging Cluster'
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/frontend-staging'
  - 'my-container=gcr.io/$PROJECT_ID/gcpdemo:$TAG_NAME'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-f'
  - 'CLOUDSDK_CONTAINER_CLUSTER=spinnaker-tutorial'
  - 'CLOUDSDK_CORE_PROJECT=$PROJECT_ID'
options:
 machineType: 'N1_HIGHCPU_8'
