kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend-production
  template:
    metadata:
      name: frontend
      labels:
        app: frontend-production
        role: frontend
        env: prod
    spec:
      containers:
      - name: my-container
        image: gcr.io/cicd-event-march25th-prod/gcpdemo:p4.1.9
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - name: frontend
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
