kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: frontend-production
spec:
  replicas: 1
  strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 1
  template:
    metadata:
      name: frontend
      labels:
        app: sample
        role: frontend
        env: prod
    spec:
      containers:
      - name: my-container
        image: gcr.io/cicd-event-march25th-prod/gcpdemo:p4.1.9
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
        env:
        - name: COMPONENT
          value: frontend
        - name: BACKEND_URL
          value: http://sample-backend-canary:8080/metadata
        - name: VERSION
          value: prod
        ports:
        - name: frontend
          containerPort: 8080
