apiVersion: v1
kind: Service
metadata:
  annotations:
    configmanagement.gke.io/cluster-selector: gcp-cluster
  labels:
    app: frontend-production
  name: frontend-production
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: frontend-production
  sessionAffinity: None
  type: LoadBalancer
